export default {
  problemStatements: [
    [
      "a Web App",
      "a tvOS app",
      "an Android Auto/Apple Car Play",
      "a watchOS app",
      "an iOS app",
      "an Android app",
      "a macOS app",
    ],
    [
      "shopping",
      "dating",
      "helping the environment",
      "video streaming",
      "music streaming",
      "improving health and fitness",
      "finding recipes",
      "finding jobs",
      "Improving mental health",
      "organising a revolution",
    ],
    [
      "wine tasters",
      "senior citizens",
      "bibliophiles",
      "people with financial issues",
      "demons",
      "aliens",
      "wizards",
      "theoretical physicists",
      "astrologer",
      "developers",
      "pet owners",
      "super heroes",
    ],
  ],
  pendingInvite: "Pending",
  acceptedInvite: "Accepted",
  rejectedInvite: "Rejected",

  branding: "Branding",
  marketing: "Marketing",
  vfx: "VFX",
  uiux: "UI/UX",
  interactiveDesign: "Interaction Design",
  visualDesign: "Visual Design",
  grpahicsDesign: "Graphic Design",

  figma: "Figma",
  sketch: "Sketch",
  framer: "Framer",
  adobeXd: "Adobe XD",
  illustrator: "Illustrator",
  afterEffects: "After Effects",
  webflow: "Webflow",
  protopie: "Protopie",
  invision: "Invision",
  principle: "Principle",

  twitter: "Twitter",
  instagram: "Instagram",
  facebook: "Facebook",
  linkedin: "Linkedin",
  email: "Email",
  discord: "Discord",
  slack: "Slack",
  reddit: "Reddit",
  wordOfMouth: "Word of Mouth",
} as const;
