export default {
  problemStatements: [
    ["website", "mobile app", "tv app", "fridge app"],
    ["restaurant", "office", "school", "collegr"],
    ["aliens", "pets", "birds", "humans"],
  ],
  pendingInvite: "Pending",
  acceptedInvite: "Accepted",
  rejectedInvite: "Rejected",

  branding: "Branding",
  marketing: "Marketing",
  vfx: "VFX",
  uiux: "UI/UX",
  interactiveDesign: "Interaction Design",
  visualDesign: "Visual Design",
  grpahicsDesign: "Graphic Design",

  figma: "Figma",
  sketch: "Sketch",
  framer: "Framer",
  adobeXd: "Adobe XD",
  illustrator: "Illustrator",
  afterEffects: "After Effects",
  webflow: "Webflow",
  protopie: "Protopie",
  invision: "Invision",
  principle: "Principle",

  twitter: "Twitter",
  instagram: "Instagram",
  facebook: "Facebook",
  linkedin: "Linkedin",
  email: "Email",
  discord: "Discord",
  slack: "Slack",
  reddit: "Reddit",
  wordOfMouth: "Word of Mouth",
} as const;
